### PR TITLE
Kibana Discover app link 7.4/7.5/7.6/7.7/7.8/7.9/7.10 support

### PR DESCRIPTION
**Pull request by nsano-rururu**

### CODE REVIEW

**Review by JeffAshton — APPROVED** [review]

**Comment by nsano-rururu** [comment]
@JeffAshton 

Thank you for your review.
Marge gave up. Elast Alert is dead

**Comment by JeffAshton** [comment]
@nsano-rururu ,  Did you want to connect about a joint fork?

**Comment by nsano-rururu** [comment]
I gave up merging this

**Comment by nsano-rururu** [comment]
Goodbye

**Comment by JeffAshton** [comment]
@nsano-rururu

I agree.  Yelp seems to have given up, but I know you mentioned interest in the past about being a maintainer.  We could fork and share our efforts.

**Comment by nsano-rururu** [comment]
@JeffAshton

I'm a co-maintainer of [elastalert-server](https://github.com/johnsusek/elastalert-server) and [praeco](https://github.com/johnsusek/praeco), so I was worried about bugs in elastalert and definitely wanted to be a maintainer. However, I'm impatient, so I don't think it's suitable for the maintainer of elastalert. If elastalert development resumes, we will reopen this pull request.

**Comment by nsano-rururu** [comment]
@JeffAshton

Kibana Discover also worked with Kibana 7.11 with additional settings. Added Kibana Discover settings to Praeco, which outputs elastalert yaml from the screen.
https://github.com/johnsusek/praeco/issues/318

**Pull request closed without merging**
