### PR TITLE
change filter:-query to filter:-query_string:

### PR DESCRIPTION
**Pull request by igbelousov**
following documentation creates this error:
RequestError(400, u'parsing_exception', {u'status': 400, u'error': {u'line': 1, u'root_cause': [{u'reason': u'no [query] registered for [query]', u'type': u'parsing_exception', u'line': 1, u'col': 208}], u'type': u'parsing_exception', u'reason': u'no [query] registered for [query]', u'col': 208}})

### CODE REVIEW

**Comment by Qmando** [comment]
What version of elastalert are you using and how are you running it?

This error should have been fixed already.

**Comment by igbelousov** [comment]
when rule configured as specified in doc, with extra query keyword:

`
filter:
- query:
    query_string:
      query: "metricset.name: cpu"
`
then
v0.1.8 (latest at time of filing pull request) fails with:  
`elastalert-test-rule --config config.yaml rules/spike-bad.yaml
Successfully loaded Events_Spike_all-hosts

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): snpstemp054
WARNING:elasticsearch:GET http://snpstemp054:9200/metricbeat-*/_search?ignore_unavailable=true&size=1 [status:400 request:0.005s]
Error running your filter:
RequestError(400, u'parsing_exception', {u'status': 400, u'error': {u'line': 1, u'root_cause': [{u'reason': u'no [query] registered for [query]', u'type': u'parsing_exception', u'line': 1, u'col': 208}], u'type': u'parsing_exception', u'reason': u'no [query] registered for [query]', u'col': 208}})`

but version v0.1.9 fails with different not related:

`
elastalert-test-rule --config config.yaml rules/spike-bad.yaml
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.1.9', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.9-py2.7.egg/elastalert/test_rule.py", line 20, in <module>
    import elastalert.config
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.9-py2.7.egg/elastalert/config.py", line 8, in <module>
    import alerts
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.9-py2.7.egg/elastalert/alerts.py", line 26, in <module>
    from twilio.base.exceptions import TwilioRestException
ImportError: No module named base.exceptions


`

So, there is no way for me to validate fix.

**Comment by Qmando** [comment]
You can fix that with ``pip install twilio==6.0.0``

**Comment by Qmando** [comment]
Closing this because an extra 'query' should work with all versions of ES, where as this version will break ES < 5.0. If you can recreate that error on the most recent version, please open an issue.

**Comment by igbelousov** [comment]
I tried with latest elastalert v0.1.12 and it works fine.
Thank you!

**Pull request closed without merging**
