### PR TITLE
Prepare for Python3

### PR DESCRIPTION
**Pull request by jarondl**
Plenty of progress towards Python2/Python3 compatibility.
This code still works with Python2, but has been made compatible
with Python3.

Some of our dependencies have to be migrated before we can announce
Python3 support, and there are other problems to solve.

50% of the work was done automatically by
python-modernize/python-modernize .

The most important change was adding `absolute_import`

### CODE REVIEW

**Comment by jarondl** [comment]
To clarify - This is not Python3 support yet, but a step in the right direction

**Comment by AndreLouisCaron** [comment]
I'm interested in seeing this ported to Python 3.5+.  Anything I can help with?

**Comment by jarondl** [comment]
That's cool @AndreLouisCaron 
Steps that need to happen before elastalert supports Python3
- [ ] Some core maintainer should tell us this will work will be merged. No point wasting our time on this PR if core is not interested. This affects a lot of files, so rebasing will be a problem the longer we wait. Also, this can be incremental, no need for full Python3 support on the first merge. @Qmando 
- [ ] exotel-py should merge this very simple PR: sarathsp06/exotel-py#5
- [ ] More Python3 conversions need to happen. See my workflow below
    
1. repackage `exotel-py` with the Python3 branch.
2. Run tox.
3. See error messages, solve some of them
4. Reiterate.

You are welcome to solve some Python3.6 errors if you want. Start from this branch, push to your fork and let me know. I will add your commits to this PR.
Generally I strive to support both Python2.7 and Python3.6 a.t.m

**Comment by AndreLouisCaron** [comment]
OK, so I got the Python 3.5+ support merged into `exotel-py`.  Waiting for a release on PyPI :-)

**Comment by Qmando** [comment]
I'm willing to merge in support for Python3 as long as it doesn't break for Python 2.

**Comment by AndreLouisCaron** [comment]
@Qmando It's not that hard to support both, we can manage that :-)

Apart from getting the test suite to pass, is there anything else you want us to do to "demonstrate" that Python 2 support is not negatively affected?

**Comment by jarondl** [comment]
Closing in favour of #1210

**Pull request closed without merging**
