### PR TITLE
Add Zalo Messenger alert type

### PR DESCRIPTION
**Pull request by phamngocduy98**
Hi guys, 
Zalo Messenger is very popular in my country. So I've writen codes to help elastalert send alert via Zalo Messenger.

Here is an example of Zalo messenger alert type
```
alert:
- "zalo"

alert_text: "Elastalert! {0}, {1}"
alert_text_args: ["type", "timestamp"]
alert_text_type: alert_text_only

zalo_bot_token: "NnpFEzGga2DH6Se_q2sV8rGRmZJLCkrs5M_"
zalo_user_id: "4859652260"
```

### CODE REVIEW

**Comment by nsano-rururu** [comment]
There are errors in the test. Source code modification required

```
py36 run-test: commands[2] | flake8.
./elastalert/alerts.py:2189:1: E302 expected 2 blank lines, found 1
./elastalert/alerts.py:2214:24: E231 missing whitespace after':'
./elastalert/alerts.py:2217:22: E231 missing whitespace after':'
./elastalert/alerts.py:2233:51: W292 no newline at end of file
```

**Comment by nsano-rururu** [comment]
I think I need to add a description of the Zalo configuration to elastalert/docs/source/ruletypes.rst.

**Comment by nsano-rururu** [comment]
@phamngocduy98 

Any way you could push this PR to https://github.com/jertel/elastalert ?
The branch is "alt". Please be careful.

**Comment by phamngocduy98** [comment]
Hello @nsano-rururu , Thanks for your information.
Now I can no longer maintain this pull request, So I closed it.

**Pull request closed without merging**
