### PR TITLE
Added support for ca_certs and client_cert

### PR DESCRIPTION
**Pull request by Qmando**
Based on https://github.com/Yelp/elastalert/pull/673

### CODE REVIEW

**Comment by runtman** [comment]
Interesting, we actually wrote in client_key as well, is this something that can be added?

**Comment by Qmando** [comment]
@runtman  sure, I'll add that in

**Comment by runtman** [comment]
Thank you so much, that's a pointless afternoon of hacking from us then :D Thanks for the assistance, I look forward to working with the tool.

**Comment by runtman** [comment]
Is that something you want me to push up or no?

**Comment by Qmando** [comment]
I'll add it

**Comment by Qmando** [comment]
@runtman 
Please test this branch out and see if it works for you!

**Comment by runtman** [comment]
Merge away, works perfectly.

`Aug 17 07:16:25 elastalert elastalert[10968]: INFO:elastalert:Ran SSH Login Detected (ubuntu) from 2017-08-16 17:59 UTC to 2017-08-17 07:16 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
Aug 17 07:16:25 elastalert elastalert[10968]: INFO:elastalert:Sleeping for 59.626792 seconds
`

`es_username: x
es_password: x
use_ssl: True
verify_certs: True
client_cert: /etc/elastalert/elastic-admin.pem
client_key: /etc/elastalert/elastic-admin-key.pem
ca_certs: /etc/elastalert/ca-bundle.pem
`

**Pull request merged**
