### PR TITLE
[WIP] Python3.8 support

### PR DESCRIPTION
**Pull request by nsano-rururu**
It's been about a year since the end of support for Pytnon 3.6, so why not change the support version to 3.8?

https://endoflife.date/python
キャプチャ

- [ ] requirements.txt and setup.py (jira> = 2.0.0 → jira> = 3.0.0)

It seems that you have to remove jira from requirements.txt and setup.py and execute the following command separately

```
pip install -U git + https://github.com/pycontribs/jira.git@3.0
```

Once jira 3.0.0 is officially released, you will need to modify requirements.txt and setup.py (jira> = 2.0.0 → jira> = 3.0.0).
Due to bug fixes for Python 3.8
https://pypi.org/project/jira/
https://github.com/pycontribs/jira/releases/tag/3.0
>Add support for Python 3.8 ([#895](https://github.com/pycontribs/jira/pull/895))

### CODE REVIEW

**Comment by nsano-rururu** [comment]
Once jira 3.0.0 is officially released, you will need to modify requirements.txt and setup.py (jira> = 2.0.0 → jira> = 3.0.0).
https://pypi.org/project/jira/
https://github.com/pycontribs/jira/releases/tag/3.0
>Add support for Python 3.8 (#895) @japz

**Comment by nsano-rururu** [comment]
When using Python3.9, blist does not work properly. 
It seems that the following pull request needs to be captured
[Python 3.9 compatibility: Use PyObject_GC_IsTracked() #91](https://github.com/DanielStutzbach/blist/pull/91)

**Comment by nsano-rururu** [comment]
configparser

Also supports Python 3.9

configparser>=3.5.0
↓
configparser>=5.0.1
https://github.com/jaraco/configparser/blob/master/CHANGES.rst

**Comment by nsano-rururu** [comment]
I want you to capture the following pull request first

[Sync requirements.txt and setup.py & update py-zabbix #2818](https://github.com/Yelp/elastalert/pull/2818)
[Pin elasticsearch to 7.0.0 in requirements.txt #2684](https://github.com/Yelp/elastalert/pull/2684)
[Fixing jira version in python3.7 #2673](https://github.com/Yelp/elastalert/pull/2673)

**Comment by nsano-rururu** [comment]
- [ ] requirements.txt and setup.py (jira> = 2.0.0 → jira> = 3.0.0)

**Comment by yunhao-qing** [comment]
Any idea when will 3.0 be officially out?

**Pull request closed without merging**
