### PR TITLE
support aws sns as alert method

### PR DESCRIPTION
**Pull request by ltagliamonte**
This PR add the support for AWS SNS service, i use the following test file:

test-rule.yaml

```
name: test rule
es_host: localhost
es_port: 9200
index: doesnmatter
type: any
alert: sns
aws_access_key: "XXXXXXX"
aws_secret_key: "XXXXXXXX"
sns_topic_arn: "arn:aws:sns:us-east-1:XXXXX"
```

data.json

```
[
 {"@timestamp": "2015-10-01",
  "foo": "bar"}
]
```

### CODE REVIEW

**Comment by Qmando** [comment]
Looks great! Thanks for adding this.

I'm going to add docs and a few minor changes and merge this in.

**Comment by Qmando** [comment]
Merged as #264

**Comment by ltagliamonte** [comment]
should update also the Readme.md in the root folder

**Comment by Qmando** [comment]
Good call

**Pull request closed without merging**
