### PR TITLE
Bearer token authorization.

### PR DESCRIPTION
**Pull request by StribPav**

### CODE REVIEW

**Comment by nsano-rururu** [comment]
Test failed

**Comment by StribPav** [comment]
@nsano-rururu Would you mind helping me to understand when a problem occurs with the build?

**Comment by nsano-rururu** [comment]
@StribPav

There seems to be a convention violation in the flake8 setting of the python source code convention check.
```
./elastalert/util.py:322:47: E251 unexpected spaces around keyword / parameter equals
./elastalert/util.py:323:47: E251 unexpected spaces around keyword / parameter equals
./elastalert/util.py:365:35: E222 multiple spaces after operator
```

**Comment by StribPav** [comment]
@nsano-rururu Test pass. What should I do next?

**Comment by nsano-rururu** [comment]
@StribPav 

Would you like to add a description of the settings you added to the document?
https://github.com/Yelp/elastalert/tree/master/docs/source

Check the documentation site to see which files to add.
http://elastalert.readthedocs.org/

Refer to the following information for checking the display of the revised document.
https://github.com/Yelp/elastalert#documentation

**Comment by StribPav** [comment]
@nsano-rururu I added to a docs description of the bearer token.  What do I have to add else?

**Comment by nsano-rururu** [comment]
There are two es_bearers. mistake?

```
+--------------------------------------------------------------+           |
| ``es_bearer`` (string, no default)                           |           |
+--------------------------------------------------------------+           |
| ``es_bearer`` (string, no default)                           |           |
+--------------------------------------------------------------+           |
```

**Comment by nsano-rururu** [comment]
I'm increasing "python-magic> = 0.4.15", but it's erased in the past commit history. Is it actually necessary and added for some action?
https://github.com/Yelp/elastalert/commit/ea62cf4bd1a62be3616f40992d088e58e2727f40

**Comment by nsano-rururu** [comment]
test code？
https://github.com/Yelp/elastalert/tree/master/tests

**Comment by akilada** [comment]
Hi,

Is this going to merge to master? 

If not, how can I use the bearer token option?

**Comment by nsano-rururu** [comment]
@akilada

> If not, how can I use the bearer token option?

Is it docker? Or is it a direct installation? .. For docker, do you have knowledge of dockerfile?

> Is this going to merge to master?

I have no idea if it will be merged.
This project is currently dormant and we do not know when it will be moved to another owner, as noted in the comments below. It may be months or years later. No one knows.

https://github.com/Yelp/elastalert/issues/2947#issuecomment-772070748
>Hi, sorry for the lack of updates
>
>We have started the process of moving this to new owners. Still working on the details. I appreciate everyone's patience.

**Comment by nsano-rururu** [comment]
elastalert is dead. You should look for another

**Comment by nsano-rururu** [comment]
@StribPav

Any way you could push this PR to https://github.com/jertel/elastalert ?

**Pull request closed without merging**
