### PR TITLE
Support es5

### PR DESCRIPTION
**Pull request by Qmando**
Initial es5 support.

create -> index everywhere.
Tests assume ES 2.
Queries use two formats, one for ES<5 and one for ES>=5.

Note:
-  test_rule.py not changed yet.
-  Old query string queries need to be changed.
-  Aggregations don't work yet.
-  Not very well tested, very much a work in progress

### CODE REVIEW

**Comment by k2xl** [comment]
nice work. LGTM

**Comment by Alexwii** [comment]
Hello.

I'm meet a bug, I don't know if it's my conf who is bad. But I have this error after elastalert-test-rule :

> RequestError(400, u'parsing_exception', {u'status': 400, u'error': {u'line': 1, u'root_cause': [{u'reason': u'no [query] registered for [filtered]', u'type': u'parsing_exception', u'line': 1, u'col': 24}], u'type': u'parsing_exception', u'reason': u'no [query] registered for [filtered]', u'col': 24}})

My query:

> filter:
> - query_string:
>         query: "severity:critical OR severity:alert"

**Comment by Alexwii** [comment]
Hello!

I have an error when I test my config file and after all seem good...: 
```
elastalert-test-rule test2.yaml
Successfully loaded Testing rule

WARNING:elasticsearch:GET http://127.0.0.1:9200/logstash-*/snmptrap/_count?ignore_unavailable=true [status:400 request:0.003s]
Error querying Elasticsearch:
RequestError(400, u'parsing_exception', {u'status': 400, u'error': {u'line': 1, u'root_cause': [{u'reason': u'no [query] registered for [filtered]', u'type': u'parsing_exception', u'line': 1, u'col': 24}], u'type': u'parsing_exception', u'reason': u'no [query] registered for [filtered]', u'col': 24}})
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
INFO:elastalert:Queried rule Testing rule from 2016-11-29 16:25 CET to 2016-11-29 17:10 CET: 2 / 2 hits
INFO:elastalert:Queried rule Testing rule from 2016-11-29 17:10 CET to 2016-11-29 17:55 CET: 6 / 4 hits
INFO:elastalert:Queried rule Testing rule from 2016-11-29 17:55 CET to 2016-11-29 18:40 CET: 9 / 3 hits
...
```

**Comment by Alexwii** [comment]
Ok, I just need to precise the global conf with

**Comment by matthillary** [comment]
I'm getting this error while running this branch on against my es5:

```
Error running your filter:
RequestError(400, u'parsing_exception', {u'status': 400, u'error': {u'line': 1, u'root_cause': [{u'reason': u'no [query] registered for [filtered]', u'type': u'parsing_exception', u'line': 1, u'col': 68}], u'type': u'parsing_exception', u'reason': u'no [query] registered for [filtered]', u'col': 68}})
```

My filter looks like this:

```
filter:
- query:
    query_string:
      query: "field: blargh"
```

any ideas?

Thanks!

**Comment by Qmando** [comment]
@matthillary Are you using ``use_count_query`` or ``use_terms_query``?

**Comment by matthillary** [comment]
@Qmando Huge thanks for the quick reply! 

The type == any (http://elastalert.readthedocs.io/en/latest/ruletypes.html#any).

It worked with the previous ES version, but not with ES5. Hopefully that gives enough information to help! Let me know what else I can provide to help troubleshoot!

Thanks!

**Comment by Qmando** [comment]
Is that a no to using ``use_count_query`` or ``use_terms_query``? I need to see the full rule to understand where this error is coming from.

**Comment by matthillary** [comment]
it's an `i don't know` to using either ;) sorry....

here's the full rule minus the alert info:

```
es_host: localhost
es_port: 9200

name: private_info_access

type: any

index: audit_events-*

filter:
- query:
    query_string:
      query: "entity_name: PrivateInfo"

alert:
- "email"
- "slack"
```

I hope that helps?

**Comment by Alexwii** [comment]
Can you test that ? I had this same error before and now it's ok 

```
filter:
 - query_string:
     query: "entity_name:PrivateInfo"
```

**Comment by matthillary** [comment]
Works perfectly! Thanks @Alexwii!

**Comment by Qmando** [comment]
Hmm, I thought this commit would have fixed that bug
https://github.com/Yelp/elastalert/commit/bb09323ad893b22d17e0d7cb2aa50c52db18f80d
Did you have the most recent commit checked out?

**Comment by dadadom** [comment]
The following rule configuration throws an error when being used on the ES5 branch with ES5:

```
type: spike
index: mylogs-*
threshold_cur: 25
timeframe:
  minutes: 5
spike_height: 3
spike_type: up

doc_type: logs
use_terms_query: true
terms_size: 50

query_key: server_id

include:
- loglevel

filter:
- term:
    loglevel: ERROR
- not:
    terms:
      classname: [Classname1, Classname2]

alert:
- slack
```

The error is:
```
WARNING:elasticsearch:GET http://1.2.3.4:9200/mylogs-2017.01.08/logs/_search?ignore_unavailable=true&size=0 [status:400 request:0.021s]
ERROR:root:Error running query: TransportError(400, {u'line': 1, u'root_cause': [{u'reason': u'no [query] registered for [not]', u'type': u'parsing_exception', u'line': 1, u'col': 195}], u'type': u'parsing_exception', u'reason': u'no [query] registered for [not]', u'col': 195})
```

**Comment by fengyingjie2018** [comment]
s_host: 127.0.0.1

es_port: 9200

name: Example rule

use_strftine_index: true

type: frequency

index: :cache-diags*

num_events: 1

timeframe:
  hours: 1
 # minutes: 1
filter:
- query_string:
    query: "message:*truncated"
smtp_host: smtp.163.com
smtp_prot: 25
smtp_ssl: false


error :
WARNING:elasticsearch:GET http://127.0.0.1:9200/elastalert_status/elastalert/_search?size=1000 [status:400 request:0.269s]
ERROR:root:Error finding recent pending alerts: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [alert_time] in order to sort on') {'sort': {'alert_time': {'order': 'asc'}}, 'query': {'bool': {'filter': {'range': {'alert_time': {'to': '2018-01-26T06:17:37.337638Z', 'from': '2018-01-25T06:17:37.337614Z'}}}, 'must': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}}}}

这是为什么呢？那里有错误么

**Comment by Qmando** [comment]
@fengyingjie2018  
你首先需要使用elastalert-create-index

**Pull request merged**
