### PR TITLE
Add Kibana Plugin and Docker install

### PR DESCRIPTION
**Pull request by RubieV**
elastalertsamplerule

### CODE REVIEW

**Comment by Qmando** [comment]
Pretty awesome!

**Comment by kureus** [comment]
This looks really cool. Tho unfortunately the RESTful API part of the project only [officially supports](https://github.com/bitsensor/elastalert/blob/master/README.md#requirements) v0.0.96, which doesn't support elastic stack v5. A previous pull request had been opened to bring an API to the main repo (#656), which would avoid any version drift issues. @Qmando what are your thoughts on getting some form of http api inside the main repo?

**Comment by RubieV** [comment]
Actually, we're running trunk so do support ES 5. Let me clarify:

Dockerfile:
RUN git clone https://github.com/Yelp/elastalert.git -b master --depth=1
/opt/elastalert

There is indeed risk on API change in master, and this is currently not
tested in CI. When this happens we will pin the last commit that we're able
to support, open an issue, and accept a pull to enable compatibility. Our
builds run on every commit, so that keeps backward compatibility with older
versions of ElastAlert.

Op ma 20 feb. 2017 om 14:37 schreef Dan Quirk <notifications@github.com>:

**Comment by kureus** [comment]
@RubieV Thanks for the clarification. Did you consider looking to get the restful api inside the elastalert repo?

**Comment by RubieV** [comment]
Yes, we chose an approach that would work with existing installations that would potentially have modifications or would have a specific version or would otherwise not be replaceable. As Node is already available due to Kibana, it is a lightweight approach.

Exposing the API from ElastAlert is better in terms of refactorability and tests are checked in with the code. I think that now we have provided the Kibana plugin, using the API that is defined makes it easy to move forward.

We use `master`, and will provide support for the `v0.1.8` API.

**Pull request merged**
