### PR TITLE
Change Library blist to sortedcontainers

### PR DESCRIPTION
**Pull request by nsano-rururu**
I've found that blist hasn't been updated for quite some time and that it doesn't work properly in Python 3.9, 
so I suggest changing it to another library.

Related issue
https://github.com/Yelp/elastalert/issues/2983

### CODE REVIEW

**Comment by nsano-rururu** [comment]
There seems to be a problem with blist even in python 3.7
https://github.com/Yelp/elastalert/issues/2693

**Comment by marc-** [comment]
Didn't have any issues on 3.7 or 3.8 . Popped up only in 3.9 on Debian and Alpine linux . On Alpine downgrading to 3.8 solves it.

**Comment by AnthraX1** [comment]
Can someone please merge this in and push to pypi? It's currently broken on Fedora 33 with python 3.9

**Comment by nsano-rururu** [comment]
@AnthraX1 

Elast Alert is no longer properly maintained. I don't think there is a pypi release.
I think I have to clone the git repository, modify the source, and do it with python setup.py install.

**Pull request closed without merging**
