### PR TITLE
Feature/advanced post alerter

### PR DESCRIPTION
**Pull request by brianmpollack**
Added alerter to send JSON to generic HTTP POST endpoint.

### CODE REVIEW

**Comment by Qmando** [comment]
How does this differ from https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L1326?

**Comment by brianmpollack** [comment]
My new post alerter allows the user to define the POST key for each Elasticsearch key. For example, in Elasticsearch there might be a key called "clientip" but you want the key when it gets sent to the endpoint to be "ip". The user can also define static values that get sent to the endpoint, such as their authentication credentials.

The reason I added this is that I have endpoints which I cannot customize, but want to POST data to them. I had to conform to their key/value structure.

I agree. Would you prefer that I incorporated this into the "Simple" post alerter and just call it "PostAlerter"? I can then add documentation for the alerter as a whole.

**Comment by Qmando** [comment]
I'd prefer they be merged into a single alerter. You can drop the word "Simple" 😄

**Comment by brianmpollack** [comment]
Thanks! Sounds good. I combined them, updated the names, and updated the documentation.

As a brief summary, if you leave the http_post_payload field undefined, it will just send all the Elasticsearch keys as-is.

**Comment by FraVieMor** [comment]
Hi!
I want do a HTTP Post to a different url (and payload) for each match. I think that this PR is useful for me. I was looking for an alert to get this behavior. Thanks!

Would be great if it is documented.

**Comment by brianmpollack** [comment]
@FraVieMor I'm glad this will be useful to you! I have documentation in the docs/source/ruletypes file that will be automatically added to the online documentation if this PR gets approved.

**Comment by av3ri** [comment]
@brianmpollack @Qmando this is awsesome! I got a chance to test the new alerter and it works really well. 😊 May I suggest a small enhancement? The ability to add header values to the post. I was able to do it in the alert.py file manually but it would be perfect if you could define them in the alert. E.g: "Authentication" for token based webhooks.

**Comment by brianmpollack** [comment]
@av3ri I'm glad you like it! That's funny, I actually was thinking of that the other day. I may add that when I get the time. As a quick tip, if you're using basic HTTP authentication, you can do http(s)://username:password@example.com/foo/ rather than adding to the header.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#Access_using_credentials_in_the_URL

**Comment by av3ri** [comment]
@brianmpollack haha great minds think alike! 😊thanks! Yes that's definitely a handy tip! Looking forward to seeing how you go. Thanks again for your efforts with making the post alerter even better. I am currently using this to populate a webhook I built for HTML based email alerts. Where I have a lot more freedom to customise the email alert.

**Pull request merged**
