### PR TITLE
scrolling support

### PR DESCRIPTION
**Pull request by omercnet**
this solves #626

### CODE REVIEW

**Comment by Qmando** [comment]
Thanks a ton for doing this! Can you add a small section to the docs as well?
I'll test this out today and then merge if everything looks good.

**Comment by omercnet** [comment]
hi @Qmando did you had a chance to test this? added docs

**Comment by Qmando** [comment]
Finally got a chance. Awesome work!

**Comment by omercnet** [comment]
Thanks @Qmando ! happy to help :)

**Comment by tanyewei** [comment]
mark

**Pull request merged**
