### PR TITLE
Thread based rule execution and scheduling

### PR DESCRIPTION
**Pull request by Qmando**
Work in progress!

First pass at adding

1. Threading execution with run_every defined per rule, partially copied from #1128
2. A rule scheduler, inspired by #1114

Note that I haven't *added* any tests yet for these features, I merely fixed the existing tests and have done some manual testing. I mostly wanted to get something up for comment before I continue testing all the edge cases.

### CODE REVIEW

**Comment by y-trobinso** [comment]
lgtm, once conflicts are resolved. I suspect this will also require an incremental change or two, since thread safety is not easy to add to a serial file.

Fixit, shipit, and post any follow-up if needed.

**Comment by chris-zhu** [comment]
@Qmando Any word on the status of this? I really would like this functionality on something I'm working on, and if you've finished working on this then I wouldn't mind helping close this PR off. I still need to familiarize with the code though so any knowledge transfer would be appreciated.

**Comment by Qmando** [comment]
@chris-zhu Hey, sorry I haven't done anything here in a while, been pretty busy. This is mostly blocked on getting more testing done. If you want to help, check out the branch and test it out yourself. I'm gonna kick off some tests overnight today and I'll report back this week.

**Comment by chris-zhu** [comment]
@Qmando For the time being then I'll use your branch in my project. I'll let you know if I encounter any issues along with any fixes if I can think of them. If there are specific testing requirements remaining for this branch to get merged in let me know what they are; I would be glad to help.

**Comment by alxArad** [comment]
Is there any chance this branch will be merged into master (especially for ES6 compatibility)? I need it because I have a few rules and each one of them needs different interval for alerting( one 2 times per day and one from hour to hour)

**Comment by burandobata** [comment]
+1

**Comment by fotag** [comment]
+1

**Comment by ChrisCooney** [comment]
+1 this is preventing us using the library.

**Comment by Dilaw9** [comment]
+1

**Comment by lsoumille** [comment]
@Qmando Any update on this, I'm realy interested to have threading support

**Comment by skbly7** [comment]
+1 This will be extremely useful for rules taking long time to execute in our setup.

**Comment by Qmando** [comment]
Hello all. Sorry for the long delay in updates. I've fixed this up and merged it with the latest changes. I'm abandoning this particular pull request in favor of pushing everything to a `beta` branch so I can release new features together as a beta version.

**Pull request closed without merging**
