### PR TITLE
Add support for ssl client certificate authentication.

### PR DESCRIPTION
**Pull request by broskos**
Minor updates to add support for client certificate authentication.

Required fields detailed in config.yaml.example.

Closes: https://github.com/Yelp/elastalert/issues/543

### CODE REVIEW

**Comment by sathieu** [comment]
Oups. I've done similar in #693

**Comment by garethahealy** [comment]
Will this be merged? I require two-way auth, which this looks like will provide some of that functionality.

**Comment by garethahealy** [comment]
@broskos any interest in rebasing your changes so they can be merged with what @sathieu did?

**Comment by broskos** [comment]
Gareth,

I'll have a look and see if I can get it rebased - thanks for the note.

Brent

Brent Roskos
Senior Cloud Architect
Cloud Infrastructure Practice
Red Hat Consulting
678-744-3623

**Comment by richm** [comment]
I did something similar for curator, which is like elastalert is based on elasticsearch-py, and for elasticsearch-py.  See https://github.com/elastic/curator/pull/570
I would strongly encourage you to support separate cert/key files in addition to the case where the key is included in the cert file.

**Comment by tux-o-matic** [comment]
Will this ever be re-based and merged?

**Comment by runtman** [comment]
+1, it seems the code is really far behind now in order for me to just copy the changes.

**Comment by Qmando** [comment]
Today is your lucky day: https://github.com/Yelp/elastalert/pull/1289

**Comment by runtman** [comment]
Haha, thank you. I added a question regarding key as we actually manually made these changes already, but it looks like we did it slightly differently. I can push this upstream?

**Pull request closed without merging**
