### PR TITLE
Allow for "external files" in blacklist/whitelist

### PR DESCRIPTION
**Pull request by SherifEldeeb**
This will do two things:
- Add a new option to include entries  from files using a special directive `- "!file /path/to/list"`
- use a `set` instead of a `list` in the blacklist/whitelist entries, which is much faster with larger sets and deduplicates automatically.
For example:
```
blacklist:
- "evil.com"
- "hacker.org"
- "virus.cc"
- "!file /tmp/black.txt"
- "!file /tmp/black2.txt"
```
You can mix between the list entry definition formats, or use either one.
.
fixes https://github.com/Yelp/elastalert/issues/711

### CODE REVIEW

**Comment by SherifEldeeb** [comment]
fixes https://github.com/Yelp/elastalert/issues/711

**Comment by Qmando** [comment]
Can you move expand_entries into __init__? It's opening the file for every single document.

**Comment by SherifEldeeb** [comment]
Done (hopefully without breaking something else).
.
It is WAY faster now also :) 
Thanks for pointing out why.

**Comment by Qmando** [comment]
Looks good. One last request: Can you add relevant documentation? docs/source/ruletypes.rst should be the correct file. Thanks!

**Comment by SherifEldeeb** [comment]
Actually, thanks to you :)
Please inform me if there's anything else that needs to be done.

**Pull request merged**
